% Define the content of the README.md file
readmeContent = [
    "# Numerical_Example_6" newline newline ...
    "## Overview" newline newline ...
    "This folder contains the files and scripts necessary for running the numerical simulation of the sixth numerical example. The following details explain the purpose and usage of each file and subdirectory within this folder." newline newline ...
    "## Folder Structure" newline newline ...
    "### Numerical_Example_6/" newline ...
    "- `.DS_Store`: A system file created by macOS, can be ignored." newline ...
    "- **Code_for_the_files/**" newline ...
    "    - `.DS_Store`: A system file created by macOS, can be ignored." newline ...
    "    - `Evolution_Matrix_FFSP_2.m`: MATLAB script for evolution matrix computation for the FFSP algorithm." newline ...
    "    - `Evolution_Probability_FFSP_2.m`: MATLAB script for evolution probability computation in the ODE evolution." newline ...
    "    - `Exponential.m`: MATLAB script for simulating the exponential distribution." newline ...
    "    - `FFSP_2.m`: MATLAB script for FFSP method." newline ...
    "    - `Gillespie_General.m`: MATLAB script for general Gillespie algorithm simulation in this hybrid setting." newline ...
    "    - `Hidden_State.m`: MATLAB script for hidden state space computation." newline ...
    "    - `bimolecular.m`: MATLAB script for identifying bimolecular networks." newline ...
    "    - `indeces_FFSP.m`: MATLAB script for computing indices for defining the FFSP evolution matrix." newline ...
    "    - `next_reaction.m`: MATLAB script for next reaction method." newline ...
    "    - `propensity_1.m`: MATLAB script for propensity functions." newline ...
    "    - `propensity_1_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `propensity_G.m`: MATLAB script for general propensity functions." newline ...
    "    - `propensity_G_FSP.m`: MATLAB script for propensity functions specific to FSP." newline ...
    "    - `propensity_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `propensity_bimolecular_FSP.m`: MATLAB script for propensity functions for bimolecular reactions specific to FSP." newline ...
    "- **Figures/**" newline ...
    "    - `Filtering_11_cell_tight.tif`: TIFF image of filtering results for the 11th cell." newline ...
    "    - `Filtering_1_cell_tight.tif`: TIFF image of filtering results for the 1st cell." newline ...
    "    - `Filtering_5_cell_tight.tif`: TIFF image of filtering results for the 5th cell." newline ...
    "- `README.md`: This file." newline ...
    "- `create_readme.m`: MATLAB script to generate the README.md file." newline ...
    "- `data45.mat`: MATLAB data file with the trajectories of the observed cells during the experiments." newline ...
    "- `generate_directory_structure.m`: MATLAB script to generate the directory structure." newline ...
    "- `main.m`: Main MATLAB script to create the project directory." newline ...
    "- `mean_cell_intensity_open_loop.m`: MATLAB script for calculating mean cell intensity in open-loop conditions." newline ...
    "- `path_of_cells_1.mat`: MATLAB data file with the paths of cells from FFSP run generated with the script 'script_for_estimations.m'." newline ...
    "- `project_structure.md`: Markdown file explaining the project structure." newline ...
    "- `script_for_estimations.m`: MATLAB script for running the filtering estimations of the hybrid experimental setup." newline ...
    "- `script_for_plotting.asv`: Autosave version of the plotting script." newline ...
    "- `script_for_plotting.m`: MATLAB script for generating plots of the filtering estimations ." newline newline ...
    "## File Descriptions" newline newline ...
    "### Code_for_the_files/" newline ...
    "This directory contains all the MATLAB scripts necessary for simulating the sixth numerical example. Each script is responsible for different aspects of the simulation, from defining the reaction network to running particle filters and FFSP methods." newline newline ...
    "### Figures/" newline ...
    "This directory contains TIFF images of filtering results for different numbers of cells." newline newline ...
    "### data45.mat" newline ...
    "MATLAB data file with the trajectories of the observed cells during the experiments." newline newline ...
    "### generate_directory_structure.m" newline ...
    "A MATLAB script to generate the directory structure of the project." newline newline ...
    "### main.m" newline ...
    "The main MATLAB script to create the project directory." newline newline ...
    "### mean_cell_intensity_open_loop.m" newline ...
    "A MATLAB script for calculating the mean cell intensity in open-loop conditions." newline newline ...
    "### path_of_cells_1.mat" newline ...
    "MATLAB data file with the paths of cells from the FFSP run." newline newline ...
    "### project_structure.md" newline ...
    "Markdown file explaining the structure of the project and its components." newline newline ...
    "## Contributing" newline newline ...
    "Please follow the standard Git workflow for contributing to this repository:" newline ...
    "1. Fork the repository." newline ...
    "2. Create a new branch (`git checkout -b feature-branch`)." newline ...
    "3. Commit your changes (`git commit -m 'Add new feature'`)." newline ...
    "4. Push to the branch (`git push origin feature-branch`)." newline ...
    "5. Create a new Pull Request." newline newline ...
    "---" newline newline ...
    "Feel free to explore the repository, and if you have any questions or suggestions, please open an issue. Happy coding!" ...
];

% Specify the file name
fileName = 'README.md';

% Open the file for writing
fileID = fopen(fileName, 'w');

% Write the content to the file
fprintf(fileID, '%s', readmeContent);

% Close the file
fclose(fileID);

% Display a message indicating the file has been created
disp('README.md file has been created successfully.');
