% Define the content of the README.md file
readmeContent = [
    "# Introduction_PF" newline newline ...
    "## Overview" newline newline ...
    "This folder contains the files and scripts necessary for running the numerical simulation of the Introduction Particle Filtering (PF) example. The following details explain the purpose and usage of each file and subdirectory within this folder." newline newline ...
    "## Folder Structure" newline newline ...
    "### Introduction_PF/" newline ...
    "- `.DS_Store`: A system file created by macOS, can be ignored." newline ...
    "- **Code_for_the_files/**" newline ...
    "    - `Continuous_Evolution_1.m`: MATLAB script for continuous evolution processes." newline ...
    "    - `Evolution_Matrix_FFSP_2.m`: MATLAB script for evolution matrix computation." newline ...
    "    - `Evolution_Probability_FFSP_2.m`: MATLAB script for evolution probability computation." newline ...
    "    - `Exponential.m`: MATLAB script for exponential processes." newline ...
    "    - `FFSP_2.m`: MATLAB script for FFSP method." newline ...
    "    - `Gillespie_General_MAK.m`: MATLAB script for Gillespie algorithm simulation." newline ...
    "    - `Hidden_State.m`: MATLAB script for hidden state computation." newline ...
    "    - `Offsprings.m`: MATLAB script for offsprings in reactions." newline ...
    "    - `bimolecular.m`: MATLAB script for bimolecular reactions." newline ...
    "    - `indeces_FFSP.m`: MATLAB script for FFSP indices." newline ...
    "    - `jump.m`: MATLAB script for jump processes." newline ...
    "    - `next_reaction.m`: MATLAB script for next reaction method." newline ...
    "    - `particle_filter_1.m`: MATLAB script for particle filtering." newline ...
    "    - `propensity_1.m`: MATLAB script for propensity functions." newline ...
    "    - `propensity_1_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `propensity_G.m`: MATLAB script for propensity functions." newline ...
    "    - `propensity_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `sampling.m`: MATLAB script for sampling." newline ...
    "- **Figures/**" newline ...
    "    - `cartoon_microscope_without_background.png`: Image file for visualization." newline ...
    "    - `conditional_N.jpg`: Image file showing conditional N." newline ...
    "    - `mRNA_Observation_Trajectory.jpg`: Image file of mRNA observation trajectory." newline ...
    "    - `mRNA_filters_results.ai`: Adobe Illustrator file of mRNA filters results." newline ...
    "    - `mRNA_filters_results.png`: Image file of mRNA filters results." newline ...
    "    - `mRNA_protein.ai`: Adobe Illustrator file of mRNA and protein results." newline ...
    "    - `mRNA_protein.png`: Image file of mRNA and protein results." newline ...
    "- `Linear_Circuit_PF_FFSP.asv`: Version control file for MATLAB script." newline ...
    "- `Linear_Circuit_PF_FFSP.m`: MATLAB script for linear circuit PF and FFSP simulation." newline ...
    "- `generate_directory_structure.m`: MATLAB script to generate the directory structure." newline ...
    "- `main.asv`: Version control file for main MATLAB script." newline ...
    "- `main.m`: MATLAB script to create the Readme file through generate_directory_structure.m.." newline ...
    "- `project_structure.md`: Markdown file explaining the project structure." newline newline ...
    "## File Descriptions" newline newline ...
    "### Code_for_the_files/" newline ...
    "This directory contains all the MATLAB scripts necessary for simulating the Introduction Particle Filtering example. Each script is responsible for different aspects of the simulation, from defining the reaction network to running particle filters and FFSP methods." newline newline ...
    "### Figures/" newline ...
    "This directory contains various plots and images for visualizing the parameters and results when defining the Introduction Particle Filtering Network:" newline ...
    "- `cartoon_microscope_without_background.png`: Visual representation of a microscope." newline ...
    "- `conditional_N.jpg`: Visualization of conditional N." newline ...
    "- `mRNA_Observation_Trajectory.jpg`: mRNA observation trajectory plot." newline ...
    "- `mRNA_filters_results.ai`: Vector graphic of mRNA filters results." newline ...
    "- `mRNA_filters_results.png`: Image of mRNA filters results." newline ...
    "- `mRNA_protein.ai`: Vector graphic of mRNA and protein results." newline ...
    "- `mRNA_protein.png`: Image of mRNA and protein results." newline newline ...
    "### Linear_Circuit_PF_FFSP.m" newline ...
    "A MATLAB script for simulating the linear circuit using particle filtering and FFSP methods." newline newline ...
    "### generate_directory_structure.m" newline ...
    "A MATLAB script to generate the directory structure of the project." newline newline ...
    "### main.m" newline ...
    "TMATLAB script to create the Readme file through generate_directory_structure.m.." newline newline ...
    "### particles_different_N.eps" newline ...
    "An EPS file showing particles for different N, used for visualization purposes." newline newline ...
    "### project_structure.md" newline ...
    "Markdown file explaining the structure of the project and its components." newline newline ...
    "## Contributing" newline newline ...
    "Please follow the standard Git workflow for contributing to this repository:" newline ...
    "1. Fork the repository." newline ...
    "2. Create a new branch (`git checkout -b feature-branch`)." newline ...
    "3. Commit your changes (`git commit -m 'Add new feature'`)." newline ...
    "4. Push to the branch (`git push origin feature-branch`)." newline ...
    "5. Create a new Pull Request." newline newline ...
    "---" newline newline ...
    "Feel free to explore the repository, and if you have any questions or suggestions, please write an email to elena.dambrosio@bsse.ethz.ch. Happy coding!" ...
];

% Specify the file name
fileName = 'README.md';

% Open the file for writing
fileID = fopen(fileName, 'w');

% Write the content to the file
fprintf(fileID, '%s', readmeContent);

% Close the file
fclose(fileID);

% Display a message indicating the file has been created
disp('README.md file has been created successfully.');
