% Define the content of the README.md file
readmeContent = [
    "# Numerical_Example_1" newline newline ...
    "## Overview" newline newline ...
    "This folder contains the files and scripts necessary for running the numerical simulation of the first numerical example using Kalman Particle Filtering (PF) and Finite State Projection (FFSP) methods. The following details explain the purpose and usage of each file and subdirectory within this folder." newline newline ...
    "## Folder Structure" newline newline ...
    "### Numerical_Example_1/" newline ...
    "- `.DS_Store`: A system file created by macOS, can be ignored." newline ...
    "- **Code_for_the_files/**" newline ...
    "    - `Continuous_Evolution_1.m`: MATLAB script for continuous evolution processes." newline ...
    "    - `Evolution_Matrix_FFSP_2.m`: MATLAB script for evolution matrix computation." newline ...
    "    - `Evolution_Probability_FFSP_2.m`: MATLAB script for evolution probability computation." newline ...
    "    - `Exponential.m`: MATLAB script for exponential processes." newline ...
    "    - `FFSP_2.m`: MATLAB script for FFSP method." newline ...
    "    - `Gillespie_General_MAK.m`: MATLAB script for Gillespie algorithm simulation." newline ...
    "    - `Hidden_State.m`: MATLAB script for hidden state computation." newline ...
    "    - `Offsprings.m`: MATLAB script for offsprings in reactions." newline ...
    "    - `bimolecular.m`: MATLAB script for bimolecular reactions." newline ...
    "    - `indeces_FFSP.m`: MATLAB script for FFSP indices." newline ...
    "    - `jump.m`: MATLAB script for jump processes." newline ...
    "    - `next_reaction.m`: MATLAB script for next reaction method." newline ...
    "    - `particle_filter_1.m`: MATLAB script for particle filtering." newline ...
    "    - `propensity_1.m`: MATLAB script for propensity functions." newline ...
    "    - `propensity_1_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `propensity_G.m`: MATLAB script for propensity functions." newline ...
    "    - `propensity_bimolecular.m`: MATLAB script for propensity functions for bimolecular reactions." newline ...
    "    - `sampling.m`: MATLAB script for sampling." newline ...
    "- `Filters_results.jpg`: Image file showing the results of the filters." newline ...
    "- `Kalman_PF_FFSP.m`: MATLAB script to run Kalman Particle Filtering and FFSP methods." newline ...
    "- `generate_directory_structure.m`: MATLAB script to generate the directory structure." newline ...
    "- `main.m`: Main MATLAB script to run the generate_directory_structure function." newline ...
    "- `variables_for_plotting.mat`: MATLAB file containing variables for plotting and to be opened with the Kalman_PF_FFSP.m file." newline ...
    "- `README.md`: This file." newline newline ...
    "## File Descriptions" newline newline ...
    "### Code_for_the_files/" newline ...
    "This directory contains all the MATLAB scripts necessary for simulating the first numerical example. Each script is responsible for different aspects of the simulation, from defining the reaction network to running particle filters and FFSP methods." newline newline ...
    "### Filters_results.jpg" newline ...
    "An image file showing the results of the filters applied in the simulation." newline newline ...
    "### Kalman_PF_FFSP.m" newline ...
    "A MATLAB script to run the Kalman Particle Filtering and Finite State Projection methods for the first numerical example." newline newline ...
    "### generate_directory_structure.m" newline ...
    "A MATLAB script to generate the directory structure of the project." newline newline ...
    "### main.m" newline ...
    "The main MATLAB script generate the project structure through generate_directory_structure." newline newline ...
    "### variables_for_plotting.mat" newline ...
    "A MATLAB file containing variables for plotting the results of the simulations with Kalman_PF_FFSP.m." newline newline ...
    "###create_readme" newline ...
    "script for creating the README.md file." newline newline ...
    "## Contributing" newline newline ...
    "Please follow the standard Git workflow for contributing to this repository:" newline ...
    "1. Fork the repository." newline ...
    "2. Create a new branch (`git checkout -b feature-branch`)." newline ...
    "3. Commit your changes (`git commit -m 'Add new feature'`)." newline ...
    "4. Push to the branch (`git push origin feature-branch`)." newline ...
    "5. Create a new Pull Request." newline newline ...
    "---" newline newline ...
    "Feel free to explore the repository, and if you have any questions or suggestions, please send an email to elena.dambrosio@bsse.ethz.ch. Happy coding!" ...
];

% Specify the file name
fileName = 'README.md';

% Open the file for writing
fileID = fopen(fileName, 'w');

% Write the content to the file
fprintf(fileID, '%s', readmeContent);

% Close the file
fclose(fileID);

% Display a message indicating the file has been created
disp('README.md file has been created successfully.');
